#!/usr/bin/env ruby

require "tunnelme"
require 'optparse'

options = {
  tun_server: 'https://localtunnel.me',
  subdomain: nil,
  port: 3000
}

OptionParser.new do |opts|
  opts.banner = "Usage: tunnelme [options]"

  opts.on('-s', '--server=server', 'tun server') do |value|
    options[:tun_server] = value
  end

  opts.on('-d', '--domain=domain', Integer, 'subdomain') do |value|
    options[:subdomain] = value
  end

  opts.on('-p', '--port=port', Integer, 'local port') do |value|
    options[:port] = value.to_i
  end

  opts.on('-h', '--help', 'Shows this help message.') do
    puts opts
    exit
  end
end.parse!

tunnel = Tunnelme::Tunnel.new(**options)
puts "your url is: #{tunnel.url}"
tunnel.serve
